services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # Traefik webui
      - "8070:8080"
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - traefik-certificates:/letsencrypt
    restart: unless-stopped
    networks:
      - traefik


networks:
  traefik:
    external: true

volumes:
  traefik-certificates: